name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Run pytests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set timezone
      uses: szenius/set-timezone@v1.2
      with:
        timezone: 'Europe/Kyiv'
    
    - name: Set up Python 3.12.6
      uses: actions/setup-python@v4
      with:
        python-version: 3.12.6
        cache: 'pip'

    - uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        python -m pip install --upgrade pip setuptools wheel httpx pytest pytest-md pytest-emoji pytest-dotenv pytest-asyncio
        pip install -r requirements.txt

    - name: Run tests
      run: pytest
    #- uses: pavelzw/pytest-action@v2
    #  with:
    #    emoji: false
    #    verbose: false
    #    job-summary: true

  build:
    name: Build docker image
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v4
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ vars.IMAGE_NAME }}:$(date +%s)
